language: python

dist: trusty
timeout: 1000

matrix:
  include:

# linux + python

    - os: linux
      python: 2.6
      name: ubuntu 14.04 - python@2.6
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 2.7
      name: ubuntu 14.04 - python@2.7
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.3
      name: ubuntu 14.04 - python@3.3
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.4
      name: ubuntu 14.04 - python@3.4
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.5
      name: ubuntu 14.04 - python@3.5
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.6
      name: ubuntu 14.04 - python@3.6
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.7
      name: ubuntu 14.04 - python@3.7
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.8-dev
      name: ubuntu 14.04 - python@3.8-dev
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

  allow_failures:
    # python2.6 and python3.3 are no longer supported by opencv
    # python3.8 does not yet supports opencv
    - name: ubuntu 14.04 - python@2.6
    - name: ubuntu 14.04 - python@3.3
    - name: ubuntu 14.04 - python@3.8-dev


before_install:
  - travis_retry eval "${MATRIX_EVAL}"
  #- pip install -r requirements.txt
  - python -m pip install numpy==1.15
  - python -m pip install Pillow==2.2.2
  - python -m pip install opencv-python
  - python -m pip install matplotlib
  - python -m pip install pytest==3.0.7
  - python -m pip install enum34
  - python -m pip install configparser
  # testing libraries
  - python -m pip install tensorflow==1.14.0
  - python -m pip install hypothesis==4.13.0

  - python -m pip install codecov
  - python -m pip install pytest-cov

install:
  - python setup.py install

script:
  - travis_wait 45 python -m pytest --cov=NumPyNet --cov-config=.coveragerc

after_succes:
  - codecov
